apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: haddock-python 
  janus-idp.io/tekton: haddock-python
  backstage.io/kubernetes-id: haddock-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: haddock-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  